name : Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: windows-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2
#       - name: Setup Python
#         uses: actions/setup-python@v3
#       - name: Run Python script
#         run: python ./src/get_num_square.py
       - name: fetch num squared
         id: get_square
         uses: ./
         with:
           num: 11
       - name: Print the square
         run: echo"{{ steps.get_square.outputs.num_squared }}"
        
